interface kmeans
{
        void init_Fragment(out Fragment frag, in File filename, in int nSize);

        @Constraints(processors={
               @Processor(ProcessorType=CPU, ComputingUnits=12)});
        void compute_newCluster(in Fragment frag, in Clusters clusters, out Clusters newClusters, out ClustersSize newClustersSize);

        void merge_newCluster(inout Clusters clusters1, in Clusters clusters2, inout ClustersSize newClustersSize1, in ClustersSize newClustersSize2);
	void update_clusters(in Clusters clusters, in ClustersSize clustersSize, inout Clusters newClusters);
};
