/* This file must be #included in the actual implementation file. */
/* This file has been autogenerated from 'Matmul.idl'. */
/* CHANGES TO THIS FILE WILL BE LOST */

#ifndef _GSS_MATMUL_H
#define _GSS_MATMUL_H
#include <c_compss.h>

typedef char* file;

enum operationCode {multiplyBlocksOp};
static const char *operationName[] = {"multiplyBlocks"};
static const int N_OPS=1;
static const int NUM_BASE_ARGS = 10;
static const int MIN_NUM_INTERNAL_ARGS = 15;
static const int METHOD_NAME_POS = 7;

/* Functions to be implemented. We suggest that you create a file */
/* with name 'Matmul-functions.cc' and implement them there. */
#include "Block.h"
void multiplyBlocks(Block* block1, Block* block2, Block* block3);

#endif /* _GSS_MATMUL_H */
