#!/bin/bash -e
  
  # Obtain parameter
  source_base_dir=$1
  target_base_dir=$2
  source_app=matmul_objects  
  # Copy files
  cp "${source_base_dir}"/execution "${target_base_dir}"/execution
  cp "${source_base_dir}"/result "${target_base_dir}"/result

  cp -r "${source_base_dir}"/"${source_app}"/src "${target_base_dir}"/src
  cp "${source_base_dir}"/"${source_app}"/*.cc "${target_base_dir}"/
  cp "${source_base_dir}"/"${source_app}"/*.idl "${target_base_dir}"/
