#!/bin/bash -e
  
  # Obtain parameter
  source_base_dir=$1
  target_base_dir=$2

  # Copy files
  cp "${source_base_dir}"/execution "${target_base_dir}"/execution
  cp "${source_base_dir}"/result "${target_base_dir}"/result

  cp -r "${source_base_dir}"/src "${target_base_dir}"
