#!/bin/bash

  # Obtain parameters
  COMPSs_exec=$1
  comm=$2
  runcompss_opts=$3
  base_app_dir=$4
  target_log_folder=$5
  compss_module=$6
  queue=$7
  qos=$8
  #Execution_envs should be the last parameter because it is a list
  execution_envs=$9
  if [ "$queue" != 'none' ]; then
          runcompss_opts="${runcompss_opts} --queue=${queue}"
  fi
  if [ "$qos" != 'none' ]; then
          runcompss_opts="${runcompss_opts} --qos=${qos}"
  fi


  # Global variables
  app_name="lysozyme_in_water_singularityExecution.py"

  #----------------------------------------------------------------------------------
  # Load COMPSs module + application
  export COMPSS_PYTHON_VERSION=3
  module load ${compss_module}

  # module load xxx
  if [ "$BSC_MACHINE" == "mn4" ]; then
  	export MDCU=48
	module load singularity/3.5.2
  elif [ "$BSC_MACHINE" == "nvidia" ]; then
	export MDCU=16
       module load singularity/3.5.2
  elif [ "$BSC_MACHINE" == "nord3" ]; then
        export MDCU=24
	module load SINGULARITY/3.2.0
  elif [ "$BSC_MACHINE" == "p9" ]; then
        export MDCU=96
        module load singularity/3.4.1
  fi	

  #----------------------------------------------------------------------------------
  # Run application
  echo
  echo "*** RUNNING PYTHON APPLICATION SIMPLE"
  for exec_env in ${execution_envs}; do
    echo "- Running with Environment: ${exec_env}"
    output_log="${target_log_folder}/${app_name}_${exec_env}.outputlog"
    error_log="${target_log_folder}/${app_name}_${exec_env}.errorlog"
    specific_log_dir="${target_log_folder}/${app_name}_${exec_env}"
    mkdir -p "${specific_log_dir}"

    job_execution_dir=${target_log_folder}
    if [ "$exec_env" == 'shared_disk' ]; then
        worker_working_dir=${specific_log_dir}
    fi
    if [ "$exec_env" == 'local_disk' ]; then
        worker_working_dir="local_disk"
    fi

    expectedTime=30
    # shellcheck disable=SC2086
    "${COMPSs_exec}" --exec_time=${expectedTime} \
      --num_nodes=2 \
      --worker_in_master_cpus=$MDCU \
      --comm="$comm" \
      --job_execution_dir=${job_execution_dir} \
      --worker_working_dir=${worker_working_dir} \
      --base_log_dir=${target_log_folder} \
      --debug \
      --summary \
      ${runcompss_opts} \
      --lang=python \
      --pythonpath="${base_app_dir}/src" \
      \
      "${base_app_dir}/src/${app_name}"  "${base_app_dir}"/config /gpfs/projects/bsc19/COMPSs_DATASETS/gromacs/2m "${base_app_dir}"/output > >(tee "${output_log}") 2> >(tee "${error_log}" >&2)


  done
