###############################################################################
########################### CREDENTIALS STAGES  ###############################
###############################################################################
ARG IMAGE
FROM ${IMAGE}

# Pass the Private SSH key
ARG SSH_PRV
ARG PD_USER

# Add the keys and set permissions
RUN mkdir -m 700 /root/.ssh && \
    echo "$SSH_PRV" > /root/.ssh/id_rsa && \
    chmod 600 /root/.ssh/id_rsa

RUN touch /root/.ssh/known_hosts; \
  ssh-keyscan dt01.bsc.es > /root/.ssh/known_hosts; \
  ssh-keyscan mn1.bsc.es >> /root/.ssh/known_hosts; \
  ssh-keyscan mn2.bsc.es >> /root/.ssh/known_hosts; \
  ssh-keyscan mn3.bsc.es >> /root/.ssh/known_hosts; \
  ssh-keyscan ela.cscs.ch >> /root/.ssh/known_hosts;

# Piz Daint credentials depends on PD_USER env. variable
#RUN ssh $PD_USER@ela.cscs.ch ssh-keyscan daint.cscs.ch >> /root/.ssh/known_hosts; exit 0

# Entry point
ENTRYPOINT ["sh", "/root/services/start.sh"]
