###############################################################################
###########################    BUILD STAGE     ################################
###############################################################################

# syntax=docker/dockerfile:experimental
#FROM registry.gitlab.com/eflows4hpc/seisensman:latest AS build
FROM registry.gitlab.bsc.es/wavephenomenagroup/ucis4eq/seisensman:latest AS build

# Install dependencies
RUN pip install --upgrade setuptools; pip install numpy flask pymongo pyyaml requests; pip install obspy webdavclient3

# Expose the Flask application port
EXPOSE 5004

# Obtain the seisEnsMan Service App
#ADD code/services/seisEnsManService.py /root/services/seisEnsManService.py

# Prepare an script able to start the slip-generator service
#RUN echo "python /root/services/seisEnsManService.py" >> /root/services/start.sh

# Start a shell
#ENTRYPOINT ["/bin/bash", "/root/services/start.sh"]
